// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/eebus-go/usecases/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"

	time "time"
)

// MuMPCInterface is an autogenerated mock type for the MuMPCInterface type
type MuMPCInterface struct {
	mock.Mock
}

type MuMPCInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MuMPCInterface) EXPECT() *MuMPCInterface_Expecter {
	return &MuMPCInterface_Expecter{mock: &_m.Mock}
}

// CurrentPerPhase provides a mock function with given fields:
func (_m *MuMPCInterface) CurrentPerPhase() ([]float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentPerPhase")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_CurrentPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPerPhase'
type MuMPCInterface_CurrentPerPhase_Call struct {
	*mock.Call
}

// CurrentPerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) CurrentPerPhase() *MuMPCInterface_CurrentPerPhase_Call {
	return &MuMPCInterface_CurrentPerPhase_Call{Call: _e.mock.On("CurrentPerPhase")}
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) Run(run func()) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) Return(_a0 []float64, _a1 error) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_CurrentPerPhase_Call) RunAndReturn(run func() ([]float64, error)) *MuMPCInterface_CurrentPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyConsumed provides a mock function with given fields:
func (_m *MuMPCInterface) EnergyConsumed() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyConsumed")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_EnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyConsumed'
type MuMPCInterface_EnergyConsumed_Call struct {
	*mock.Call
}

// EnergyConsumed is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) EnergyConsumed() *MuMPCInterface_EnergyConsumed_Call {
	return &MuMPCInterface_EnergyConsumed_Call{Call: _e.mock.On("EnergyConsumed")}
}

func (_c *MuMPCInterface_EnergyConsumed_Call) Run(run func()) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_EnergyConsumed_Call) Return(_a0 float64, _a1 error) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_EnergyConsumed_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_EnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyProduced provides a mock function with given fields:
func (_m *MuMPCInterface) EnergyProduced() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergyProduced")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_EnergyProduced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyProduced'
type MuMPCInterface_EnergyProduced_Call struct {
	*mock.Call
}

// EnergyProduced is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) EnergyProduced() *MuMPCInterface_EnergyProduced_Call {
	return &MuMPCInterface_EnergyProduced_Call{Call: _e.mock.On("EnergyProduced")}
}

func (_c *MuMPCInterface_EnergyProduced_Call) Run(run func()) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_EnergyProduced_Call) Return(_a0 float64, _a1 error) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_EnergyProduced_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_EnergyProduced_Call {
	_c.Call.Return(run)
	return _c
}

// Frequency provides a mock function with given fields:
func (_m *MuMPCInterface) Frequency() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Frequency")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_Frequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Frequency'
type MuMPCInterface_Frequency_Call struct {
	*mock.Call
}

// Frequency is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) Frequency() *MuMPCInterface_Frequency_Call {
	return &MuMPCInterface_Frequency_Call{Call: _e.mock.On("Frequency")}
}

func (_c *MuMPCInterface_Frequency_Call) Run(run func()) *MuMPCInterface_Frequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_Frequency_Call) Return(_a0 float64, _a1 error) *MuMPCInterface_Frequency_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_Frequency_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_Frequency_Call {
	_c.Call.Return(run)
	return _c
}

// Power provides a mock function with given fields:
func (_m *MuMPCInterface) Power() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Power")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_Power_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Power'
type MuMPCInterface_Power_Call struct {
	*mock.Call
}

// Power is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) Power() *MuMPCInterface_Power_Call {
	return &MuMPCInterface_Power_Call{Call: _e.mock.On("Power")}
}

func (_c *MuMPCInterface_Power_Call) Run(run func()) *MuMPCInterface_Power_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_Power_Call) Return(_a0 float64, _a1 error) *MuMPCInterface_Power_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_Power_Call) RunAndReturn(run func() (float64, error)) *MuMPCInterface_Power_Call {
	_c.Call.Return(run)
	return _c
}

// PowerPerPhase provides a mock function with given fields:
func (_m *MuMPCInterface) PowerPerPhase() ([]float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PowerPerPhase")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_PowerPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerPerPhase'
type MuMPCInterface_PowerPerPhase_Call struct {
	*mock.Call
}

// PowerPerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) PowerPerPhase() *MuMPCInterface_PowerPerPhase_Call {
	return &MuMPCInterface_PowerPerPhase_Call{Call: _e.mock.On("PowerPerPhase")}
}

func (_c *MuMPCInterface_PowerPerPhase_Call) Run(run func()) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_PowerPerPhase_Call) Return(_a0 []float64, _a1 error) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_PowerPerPhase_Call) RunAndReturn(run func() ([]float64, error)) *MuMPCInterface_PowerPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: data
func (_m *MuMPCInterface) Update(data ...api.UpdateMeasurementData) error {
	_va := make([]interface{}, len(data))
	for _i := range data {
		_va[_i] = data[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...api.UpdateMeasurementData) error); ok {
		r0 = rf(data...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MuMPCInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MuMPCInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - data ...api.UpdateMeasurementData
func (_e *MuMPCInterface_Expecter) Update(data ...interface{}) *MuMPCInterface_Update_Call {
	return &MuMPCInterface_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{}, data...)...)}
}

func (_c *MuMPCInterface_Update_Call) Run(run func(data ...api.UpdateMeasurementData)) *MuMPCInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]api.UpdateMeasurementData, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(api.UpdateMeasurementData)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MuMPCInterface_Update_Call) Return(_a0 error) *MuMPCInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_Update_Call) RunAndReturn(run func(...api.UpdateMeasurementData) error) *MuMPCInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseA provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataCurrentPhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseA")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseA'
type MuMPCInterface_UpdateDataCurrentPhaseA_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseA_Call{Call: _e.mock.On("UpdateDataCurrentPhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseA_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseB provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataCurrentPhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseB")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseB'
type MuMPCInterface_UpdateDataCurrentPhaseB_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseB_Call{Call: _e.mock.On("UpdateDataCurrentPhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseB_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataCurrentPhaseC provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataCurrentPhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataCurrentPhaseC")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataCurrentPhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataCurrentPhaseC'
type MuMPCInterface_UpdateDataCurrentPhaseC_Call struct {
	*mock.Call
}

// UpdateDataCurrentPhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataCurrentPhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	return &MuMPCInterface_UpdateDataCurrentPhaseC_Call{Call: _e.mock.On("UpdateDataCurrentPhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataCurrentPhaseC_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataCurrentPhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyConsumed provides a mock function with given fields: value, timestamp, valueState, evaluationStart, evaluationEnd
func (_m *MuMPCInterface) UpdateDataEnergyConsumed(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState, evaluationStart, evaluationEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyConsumed")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState, evaluationStart, evaluationEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataEnergyConsumed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyConsumed'
type MuMPCInterface_UpdateDataEnergyConsumed_Call struct {
	*mock.Call
}

// UpdateDataEnergyConsumed is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationStart *time.Time
//   - evaluationEnd *time.Time
func (_e *MuMPCInterface_Expecter) UpdateDataEnergyConsumed(value interface{}, timestamp interface{}, valueState interface{}, evaluationStart interface{}, evaluationEnd interface{}) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	return &MuMPCInterface_UpdateDataEnergyConsumed_Call{Call: _e.mock.On("UpdateDataEnergyConsumed", value, timestamp, valueState, evaluationStart, evaluationEnd)}
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time)) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType), args[3].(*time.Time), args[4].(*time.Time))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyConsumed_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyConsumed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataEnergyProduced provides a mock function with given fields: value, timestamp, valueState, evaluationStart, evaluationEnd
func (_m *MuMPCInterface) UpdateDataEnergyProduced(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState, evaluationStart, evaluationEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataEnergyProduced")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState, evaluationStart, evaluationEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataEnergyProduced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataEnergyProduced'
type MuMPCInterface_UpdateDataEnergyProduced_Call struct {
	*mock.Call
}

// UpdateDataEnergyProduced is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
//   - evaluationStart *time.Time
//   - evaluationEnd *time.Time
func (_e *MuMPCInterface_Expecter) UpdateDataEnergyProduced(value interface{}, timestamp interface{}, valueState interface{}, evaluationStart interface{}, evaluationEnd interface{}) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	return &MuMPCInterface_UpdateDataEnergyProduced_Call{Call: _e.mock.On("UpdateDataEnergyProduced", value, timestamp, valueState, evaluationStart, evaluationEnd)}
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType, evaluationStart *time.Time, evaluationEnd *time.Time)) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType), args[3].(*time.Time), args[4].(*time.Time))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataEnergyProduced_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType, *time.Time, *time.Time) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataEnergyProduced_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataFrequency provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataFrequency(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataFrequency")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataFrequency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataFrequency'
type MuMPCInterface_UpdateDataFrequency_Call struct {
	*mock.Call
}

// UpdateDataFrequency is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataFrequency(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataFrequency_Call {
	return &MuMPCInterface_UpdateDataFrequency_Call{Call: _e.mock.On("UpdateDataFrequency", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataFrequency_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataFrequency_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseA provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataPowerPhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseA")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseA'
type MuMPCInterface_UpdateDataPowerPhaseA_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseA_Call{Call: _e.mock.On("UpdateDataPowerPhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseA_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseB provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataPowerPhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseB")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseB'
type MuMPCInterface_UpdateDataPowerPhaseB_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseB_Call{Call: _e.mock.On("UpdateDataPowerPhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseB_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerPhaseC provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataPowerPhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerPhaseC")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataPowerPhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerPhaseC'
type MuMPCInterface_UpdateDataPowerPhaseC_Call struct {
	*mock.Call
}

// UpdateDataPowerPhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerPhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	return &MuMPCInterface_UpdateDataPowerPhaseC_Call{Call: _e.mock.On("UpdateDataPowerPhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerPhaseC_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerPhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPowerTotal provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataPowerTotal(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPowerTotal")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataPowerTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPowerTotal'
type MuMPCInterface_UpdateDataPowerTotal_Call struct {
	*mock.Call
}

// UpdateDataPowerTotal is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataPowerTotal(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataPowerTotal_Call {
	return &MuMPCInterface_UpdateDataPowerTotal_Call{Call: _e.mock.On("UpdateDataPowerTotal", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataPowerTotal_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataPowerTotal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseA provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseA")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseA'
type MuMPCInterface_UpdateDataVoltagePhaseA_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseA_Call{Call: _e.mock.On("UpdateDataVoltagePhaseA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseA_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseAToB provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseAToB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseAToB")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseAToB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseAToB'
type MuMPCInterface_UpdateDataVoltagePhaseAToB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseAToB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseAToB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseAToB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseAToB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseAToB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseB provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseB(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseB")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseB'
type MuMPCInterface_UpdateDataVoltagePhaseB_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseB is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseB(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseB_Call{Call: _e.mock.On("UpdateDataVoltagePhaseB", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseB_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseBToC provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseBToC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseBToC")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseBToC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseBToC'
type MuMPCInterface_UpdateDataVoltagePhaseBToC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseBToC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseBToC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseBToC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseBToC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseBToC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseC provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseC(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseC")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseC'
type MuMPCInterface_UpdateDataVoltagePhaseC_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseC is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseC(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseC_Call{Call: _e.mock.On("UpdateDataVoltagePhaseC", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseC_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseC_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataVoltagePhaseCToA provides a mock function with given fields: value, timestamp, valueState
func (_m *MuMPCInterface) UpdateDataVoltagePhaseCToA(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType) api.UpdateMeasurementData {
	ret := _m.Called(value, timestamp, valueState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataVoltagePhaseCToA")
	}

	var r0 api.UpdateMeasurementData
	if rf, ok := ret.Get(0).(func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData); ok {
		r0 = rf(value, timestamp, valueState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.UpdateMeasurementData)
		}
	}

	return r0
}

// MuMPCInterface_UpdateDataVoltagePhaseCToA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataVoltagePhaseCToA'
type MuMPCInterface_UpdateDataVoltagePhaseCToA_Call struct {
	*mock.Call
}

// UpdateDataVoltagePhaseCToA is a helper method to define mock.On call
//   - value float64
//   - timestamp *time.Time
//   - valueState *model.MeasurementValueStateType
func (_e *MuMPCInterface_Expecter) UpdateDataVoltagePhaseCToA(value interface{}, timestamp interface{}, valueState interface{}) *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call {
	return &MuMPCInterface_UpdateDataVoltagePhaseCToA_Call{Call: _e.mock.On("UpdateDataVoltagePhaseCToA", value, timestamp, valueState)}
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call) Run(run func(value float64, timestamp *time.Time, valueState *model.MeasurementValueStateType)) *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(*time.Time), args[2].(*model.MeasurementValueStateType))
	})
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call) Return(_a0 api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call) RunAndReturn(run func(float64, *time.Time, *model.MeasurementValueStateType) api.UpdateMeasurementData) *MuMPCInterface_UpdateDataVoltagePhaseCToA_Call {
	_c.Call.Return(run)
	return _c
}

// VoltagePerPhase provides a mock function with given fields:
func (_m *MuMPCInterface) VoltagePerPhase() ([]float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VoltagePerPhase")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MuMPCInterface_VoltagePerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoltagePerPhase'
type MuMPCInterface_VoltagePerPhase_Call struct {
	*mock.Call
}

// VoltagePerPhase is a helper method to define mock.On call
func (_e *MuMPCInterface_Expecter) VoltagePerPhase() *MuMPCInterface_VoltagePerPhase_Call {
	return &MuMPCInterface_VoltagePerPhase_Call{Call: _e.mock.On("VoltagePerPhase")}
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) Run(run func()) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) Return(_a0 []float64, _a1 error) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MuMPCInterface_VoltagePerPhase_Call) RunAndReturn(run func() ([]float64, error)) *MuMPCInterface_VoltagePerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMuMPCInterface creates a new instance of MuMPCInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMuMPCInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MuMPCInterface {
	mock := &MuMPCInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
